name: Terraform Plan

on:
  workflow_dispatch

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    name: Terraform plan
    defaults:
      run:
        working-directory: ${{ github.workspace }}/infrastructure/environments/dev/service_dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET  }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID  }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: terraform init
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ~1.0
          terraform_wrapper: false

      # Generates an execution plan for Terraform
      - name: terraform plan
        run: | 
          terraform init 
          terraform plan -out plan.out
      - name: upload terraform plan
        uses: actions/upload-artifact@v2
        with:
          name: practice_plan
          path: ${{ github.workspace }}/infrastructure/environments/dev/service_dev/plan.out
