name: Terraform Plan

on:
  workflow_dispatch

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create Terraform plan
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          with:
            creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET  }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID  }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
            enable-AzPSSession: true 

      - name: terraform init
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
  
      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -input=false